---
title: "beer_data_analysis"
author: "Pei Yu Lin"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
#install.packages("tidyverse")
#install.packages("dplyr")
#install.packages("emmeans")
#install.packages("data.table")
#install.packages("Hmisc")
#install.packages("car")
#install.packages("gridExtra")
# install.packages("ggpmisc")
# install.packages("patchwork")

library(tidyverse)
options(width=100)
library(dplyr)
library(emmeans)
library(data.table)
library(Hmisc)
library(car)
library(gridExtra)
library(ggpmisc)
library(patchwork)
```

---

# Section 1 - data management and statistics

```{R Data preparation}
# Read in the data
beer_data <- read_csv("Craft-Beer_data_set.txt")

# Check data structure
str(beer_data)

# Categorize data into general categories by detecting strings or category 
# identifiers in Style column
new_beer_data <- beer_data%>%
  mutate(category = ifelse(Style %like% "IPA", "IPA", 
                    ifelse(Style %like% "Lager", "Lager", 
                    ifelse(Style %like% "Porter", "Porter", 
                    ifelse(Style %like% "Stout", "Stout", 
                    ifelse(Style %like% "Wheat", "Wheat", 
                    ifelse(Style %like% "Pale", "Pale", 
                    ifelse(Style %like% "Pilsner", "Pilsner",
                    ifelse(Style %like% "Bock", "Bock", "Others")))))))))

# Check data value
summary(new_beer_data) 
# discover outliers in the data set
```

```{R plots of the distribution , message=FALSE, warning=FALSE}
# Visualize data and check their distributions

## Rating
rating.plot <- ggplot(new_beer_data, aes(x=rating, y=..density..)) + 
  geom_histogram(binwidth = 0.05) + geom_density(col = "red") + 
  labs(title="the distribution of the rating")

rating.plot # normal distribution

# ABV
ABV.plot <- ggplot(new_beer_data, aes(x=ABV, y=..density..)) + 
  geom_histogram(binwidth = 1) + geom_density(col="red") + 
  labs(title="the distribution of the ABV")

ABV.plot # normal distribution

# Sweet
Sweet.plot <- ggplot(new_beer_data, aes(x=Sweet, y=..density..)) + 
  geom_histogram(binwidth = 5) + geom_density(col="red") + 
  labs(title="the distribution of the Sweet")

Sweet.plot # normal distribution

# Malty
Malty.plot <- ggplot(new_beer_data, aes(x=Malty, y=..density..)) + 
  geom_histogram(binwidth = 5) + geom_density(col = "red") + 
  labs(title="the distribution of the Malty")

Malty.plot #normal distribution and having outliers
```

```{R Handle outliers and clean data}
# ABV
## Assume the value of ABV above 20 is an extreme values and remove the outliers
new_beer_data <- filter(new_beer_data, ABV <= 20)

# Sweet
##Assume the value of Sweet above 200 is an extreme values and 
## remove the outliers
new_beer_data <- filter(new_beer_data, Sweet <= 200)

# Malty
## Assume the value of Malty above 250 is an extreme values and 
##remove the outliers
new_beer_data <- filter(new_beer_data, Malty <= 250)

# Check the type of variable 'category' 
typeof(new_beer_data$category)
# Change it as a factor
new_beer_data$category <- as.factor(new_beer_data$category)
# Get the final number of each category
summary(new_beer_data$category)
```

**Calculate the mean rating and 95% confidence interval of the rating within each category using a linear model**

```{R linear model}
lm.rating.category <- lm(rating~category, data=new_beer_data)
emmeans.rating.category <- emmeans(lm.rating.category, ~category)
emmeans.rating.category
```

**Draw a plot that displays, on a single axes, the distribution of the ratings within each category on the same plot**

```{R the distribution of the ratings within each category}
rating.category <- ggplot(summary(emmeans.rating.category), 
                      aes(x=category, y=emmean, ymin=lower.CL, ymax=upper.CL)) + 
  geom_point() + geom_linerange(color="red") + geom_line(aes(group="category"))+
  labs(x="category",y="rating",subtitle="The mean and 95% CIs for each category") 

# Reorder the category in the plot
rating.category.order <- summary(emmeans.rating.category)
## get the order according to emmean
order.category <- rating.category.order[order(rating.category.order$emmean, 
                                              decreasing = TRUE),]$category
## reorder
new.rating.category <-  rating.category.order %>% arrange(factor(category, 
                                                  levels = order.category))

# Violin plot
violin.plot <- ggplot(new.rating.category, 
   aes(x=reorder(category, -emmean), y=emmean, ymin=lower.CL, ymax=upper.CL)) + 
  geom_point() + geom_linerange(color="red") + geom_line(aes(group="category"))+ 
  geom_violin(data = new_beer_data, 
    aes(x= category, y=rating, ymin=NULL, ymax=NULL, fill=category), alpha=0.5)+ 
  labs(subtitle = "the distribution of the ratings within each category") 
```

**Showing whether, on average, a beer receives a higher rating if it has a higher or lower ABV**

```{R Data analysis (ABV rating)}
# Use linear model to observe the relationship of rating and ABV
## NHST approach
lm.rating.ABV <- lm(rating~ABV, data=new_beer_data)
summary(lm.rating.ABV) 
## Estimation approach
cbind(coefficient = coef(lm.rating.ABV), confint(lm.rating.ABV), 
      Pr = rep("***"))

# Use graph to observe the relationship of rating and ABV
ABV.rating.plot <- ggplot(new_beer_data, aes(x = ABV, y = rating)) + 
  geom_point() + geom_smooth() + labs(title = "rating score against ABV")
ABV.rating.plot

# Correlation check
rcorr(as.matrix(select(new_beer_data,rating, ABV), type = "pearson"))
```

**Use linear model to show if having more or less Sweet or Malty elements in the flavour results in higher or lower ratings.**

```{R Data analysis (Sweet Malty ABV rating)}
#NHST approach
## Get main effect linear model
lm.sweet.malty.ABV.rating <- lm(rating~Sweet+Malty+ABV, data=new_beer_data)
summary(lm.sweet.malty.ABV.rating)

## Get interaction effect model
lm.sweet.malty.ABV.rating.interaction <- lm(rating~Sweet*Malty*ABV, 
                                            data=new_beer_data)
summary(lm.sweet.malty.ABV.rating.interaction)

## Use ANOVA to check whether adding interaction is helpful to explain the 
## dependent variable
anova(lm.sweet.malty.ABV.rating, lm.sweet.malty.ABV.rating.interaction)

better.model <- summary(lm.sweet.malty.ABV.rating.interaction)

# Estimation approach: showing the coefficient and confindence interval of the 
## better model in previous step
better.model.pvalue <- better.model$coefficients[,4]
cbind(coefficient = coef(lm.sweet.malty.ABV.rating.interaction), 
      confint(lm.sweet.malty.ABV.rating.interaction), 
      ifelse(better.model.pvalue <0.01, "***", 
      ifelse(better.model.pvalue < 0.05, "**", 
      ifelse(better.model.pvalue < 0.1, "*"," "))))

# Check whether VIF is lower than 5
vif(lm.sweet.malty.ABV.rating)
vif(lm.sweet.malty.ABV.rating.interaction)

# Apply Pearson correlation to check the statistical relationship 
## between variables
rcorr(as.matrix(select(new_beer_data,rating, ABV, Sweet, Malty), 
                type = "pearson"))
```

**test the effects of flavourings**

What flavourings should the company use more/less of if they are creating a high ABV beer?
What flavourings should the company use more/less of if they are creating a low ABV beer

```{R}
# Define low and high quantiles of ABV values and combine with all situation 
## (zero, minimum and maximum Sweet and Malty)
tibble("90th" = quantile(new_beer_data$ABV, 0.9),
"80th" = quantile(new_beer_data$ABV, 0.8),
"20th" = quantile(new_beer_data$ABV, 0.2),
"10th" = quantile(new_beer_data$ABV, 0.1))
# Since the values of 80th of ABV and 20th of ABV are close, 
## so we select the 90th and 10th of ABV to see the difference

## Set up a tibble for the prediction of rating score 
### high ABV
preds.rating.intr.highABV <-tibble(ABV =rep(quantile(new_beer_data$ABV,0.9), 4), 
                                   Sweet = rep(c(max(new_beer_data$Sweet),                                                           min(new_beer_data$Sweet)), 2), 
                                   Malty = c(rep(min(new_beer_data$Malty),2),
                                             rep(max(new_beer_data$Malty),2)))

### low ABV
preds.rating.intr.lowABV <- tibble(ABV =rep(quantile(new_beer_data$ABV,0.1), 4), 
                                   Sweet = rep(c(max(new_beer_data$Sweet),                                                            min(new_beer_data$Sweet)), 2), 
                                   Malty = c(rep(min(new_beer_data$Malty),2),
                                             rep(max(new_beer_data$Malty),2)))

## Use the better model to predict the rating score with the data in the 
## tibbles generated above and add the rating score into the tibble

### high ABV
preds.rating.intr.highABV <- mutate(preds.rating.intr.highABV, 
                    Rating.hat = predict(lm.sweet.malty.ABV.rating.interaction,                                                    preds.rating.intr.highABV), ABV = factor(ABV))

### low ABV
preds.rating.intr.lowABV <- mutate(preds.rating.intr.lowABV, 
                    Rating.hat = predict(lm.sweet.malty.ABV.rating.interaction,                                                    preds.rating.intr.lowABV),ABV = factor(ABV))

### high and low ABV
preds.rating.intr.allABV <- rbind(preds.rating.intr.highABV,
                                  preds.rating.intr.lowABV)
```

```{R the relationship individual flavouring,message=FALSE, warning=FALSE}
preds.rating.intr.allABV.f <- preds.rating.intr.allABV  
# Change factor levels
levels(preds.rating.intr.allABV.f$ABV) <- list("High" = 10,        
                               "Low" = 4.5)

by.sweet.rating <- preds.rating.intr.allABV.f %>%
  group_by(ABV, Sweet) %>%
  mutate(rating.sweet = mean(Rating.hat))

by.malty.rating <- preds.rating.intr.allABV.f %>%
  group_by(ABV, Malty) %>%
  mutate(rating.malty = mean(Rating.hat))

sweet.ABV.rating.plot <- ggplot(preds.rating.intr.allABV.f) + 
  geom_point(aes(x = Sweet, y = Rating.hat,color = ABV)) + 
  geom_line(data = by.sweet.rating, 
            aes(x=Sweet, y=rating.sweet, group=ABV, colour=ABV)) + 
  ylab("Predicted Rating") + labs(x="Sweet", y="Rating", 
                    title = "the relationship between Sweet, ABV and rating")

tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)))

# Set the legend for the column explanation
FigLegend1 <-data.frame(legend="rating.sweet: It is the mean of the rating under 
                         a specific degree of sweetness")
legend.graph.sweet <- tableGrob(FigLegend1, rows = NULL, cols = NULL,
                                theme=ttheme_minimal(base_size = 10))

# Put the table, legend and graph side by side
tbl.sweet <- tableGrob(by.sweet.rating, rows = NULL, theme=ttheme_minimal(base_size = 10))

tbl.sweet.legend <- arrangeGrob(tbl.sweet,legend.graph.sweet,nrow = 2,
                                heights = unit(c(2, 0.25),c("null", "null")))

grid.arrange(sweet.ABV.rating.plot, tbl.sweet.legend,
             nrow=1,ncol=2,
             as.table=TRUE)

malty.ABV.rating.plot <- ggplot(preds.rating.intr.allABV.f) + 
  geom_point(aes(x = Malty, y = Rating.hat, color = ABV)) + 
  geom_line(data = by.malty.rating, aes(x=Malty, y=rating.malty, group=ABV, 
            colour=ABV)) + ylab("Predicted Rating") + 
  labs(title = "the relationship between Malty, ABV and rating") 



# Set the legend for the column explanation
FigLegend2 <-data.frame(legend="rating.malty: It is the mean of the rating under 
                         a specific degree of malty")

legend.graph.malty <- tableGrob(FigLegend2, rows = NULL, cols = NULL, 
                                theme=ttheme_minimal(base_size = 10))

# Put the table, legend and graph side by side
tbl.malty <- tableGrob(by.malty.rating, rows = NULL, theme = ttheme_minimal(base_size = 10))

tbl.malty.legend <- arrangeGrob(tbl.malty,legend.graph.malty,nrow = 2,
                                heights = unit(c(2, 0.25),c("null", "null")))

grid.arrange(malty.ABV.rating.plot, tbl.malty.legend,
             nrow=1,ncol=2,
             as.table=TRUE)

```


# Section 2 - data analysis and insights

This report presents a data analysis for a beer company. The company want to know whether particular types of beers has higher rating score. In this report, beers are categorised into nine categories (IPA, Lager, Porter, Stout, Wheat, Pale, Pilsner, and Bock) by detecting the strings and identifiers shown in Style column. Afterwards, confidence intervals and means are invested, and the outcomes demonstrated that the means and CIs of rating for each category fall around 3 and 4. 

To further the investigation, most of the categories are more concentrated to their means, except for the Lager and Others categories. More specifically, the data of Lager and Others categories are more scattered according to the violin plot. That is, their ratings are various. Also, the mean of data in Lager category has a lower average rating comparing to other categories.

The company also wants to get insights from the data to design a new high-rating product. From the data, we have 5,558 beers and also their properties, including their names, rating score, and multiple flavourings.

According to the graph, linear regression, and correlation test, it can show that rating, ABV, Sweet, and Malty are all positive but low or little correlated. From the correlation test, ABV has higher correlation with rating comparing to other variables. Increasing one unit of ABV would increase the rating by an average of 0.08 points (coefficient = 0.08, 95%CI[0.0755, 0.0844]). Moreover, the p-value of ABV to the rating is significance difference (p-value < 0.05, t(5538) = 35.34), so it can be concluded that ABV is also a significant predictor towards the rating.
```{R, message=FALSE, warning=FALSE}
ABV.rating.plot
```


Furthermore, based on the historical data, it can be proved that as the ABV increases, the rating would increase.

Further, based on the model comparison between main effect and interaction effect model (ANOVA test), it can be concluded that the interaction effect model is better because the p-value is less than 0.001, which means the model with the interaction term is significantly improved (F(4, 5532) = 27.827, p-value < 0.001). Thus, the interaction term should be considered when analyze the data.

From the interaction effect model, we can see that Sweet, Malty, and ABV are significant predictors of the model with the p-value lower than 0.001. Moreover, only Malty negatively affects the rating, which means increasing one unit of Malty would decrease 0.003 in the rating. For the Sweet property, increasing one unit of Sweet would lead to an increase of 0.00638 points towars rating(p-value < 0.001, t(5532) = 8.355, coefficient = 0.00638, 95%CI[0.0049, 0.0079]).

For the interaction term only the interaction of Sweet and ABV and the interaction of Malty of ABV are associated with rating. What's more, the interaction of Sweet and ABV is negatively associated to the rating (p-value < 0.001, t(5532) = 6.265, coefficient = -0.0006223, 95%CI[-0.0008, -0.0004]). Although ABV has a positive impact (p-value < 0.001, t(5532) = 13.942, coefficient = 0.08, 95%CI[0.0689, 0.0915]) towards rating, when it interacted with Sweet property, the rating would be negatively impacted. In comparison, the interaction of Malty and ABV positively influence the rating (p-value < 0.001, t(5532) = 4,886, coefficient = 0.0004669, 95%CI[0.0003, 0.0007]).

To investigate how to maximise the rating based on the variables ABV, Sweet, and Malty, the 0.9 and 0.1 quantile of ABV are adopted, and the maximum and minimum of Sweet and Malty are used to predict the rating with the ABV.

According to the graphs and tables about the relationship between ABV, rating, and Sweet/Malty shown above, it can be concluded that to maximise the rating, Sweet should not be added when ABV is high (quantile = 0.9). In contrary, Malty flavours has positive impact towards the rating when ABV is high (quantile = 0.9), so Malty could be added more under high ABV. Also, the rating would increase when Sweet increases or Malty decreases as ABV is low (quantile = 0.1).

According to the findings, if the company are creating a high ABV beer, they should not add Sweet but Malty. On the other hand, for the low ABV beer, the company should add more Sweet and not malty to maximise the rating score.
Accordingly, with higher or lower ABVs, the company should execute different plan to design its product.

---